service: RestAPI
frameworkVersion: '2'

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  memorySize: 2048
  timeout: 15
  region: ap-southeast-1
  vpc:
    securityGroupIds:
      - sg-0e877d7361032a269
    subnetIds:
      - subnet-0fb69a83a2f67b644
      - subnet-0ac8f067660edbe3a
      - subnet-0571022f6ba208cbe

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true
    environment:
      PORT: 3050
      NODE_ENV: dev
      MONGO_URI: mongodb+srv://rod:qwe@cluster0.ws75w.mongodb.net/rod
