service: RestAPI
frameworkVersion: '2'

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  memorySize: 2048
  timeout: 15
  region: ap-southeast-1
  vpc:
    securityGroupIds:
      - sg-0c6211b6d07438ef2
    subnetIds:
      - subnet-0deeaf65066a1cfbf
      - subnet-0bd930ef6439bcce2
      - subnet-0effd43327a3572b5

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true
    environment:
      PORT: 3050
      NODE_ENV: dev
      MONGO_URI: mongodb+srv://rod:admin@cluster0.ws75w.mongodb.net/
